version: '3'

services:
  beanstalkd: 
    image: schickling/beanstalkd
  worker: 
    image: helenyfung/aftership_worker
    depends_on: 
      - beanstalkd
      - mongodb
    environment:
      EXCHANGE_API_KEY: ${EXCHANGE_API_KEY}
  mongodb: 
    image: mongo
